cargo-features = ["edition"]

[package]
name = "eris"
version = "0.1.0"
authors = ["Celti Burroughs <celti@celti.name>"]
edition = "2018"

[dependencies]
bincode = "1"
chrono = "0.4"
ddate = "0.4"
dotenv = "0.13"
env_logger = "0.5"
failure = "0.1"
failure_derive = "0.1"
exitfailure = "0.4"
fnorder = "1"
indoc = "0.2"
lazy_static = "1"
log = "0.4"
log-panics = "2"
maplit = "1.0"
matches = "0.1"
parking_lot = "0.6"
#pest = "1"
#pest_derive = "1"
rand = "0.5"
regex = "1"
rustbreak = { version = "2.0.0-rc2", features = ["bin_enc"] }
serenity = "0.5"
typemap = "0.3"
