[package]
name = "eris"
version = "0.4.0"
authors = ["Celti Burroughs <celti@celti.name>"]

[dependencies]
chrono = "0.4"
ddate = "0.4"
env_logger = "0.4"
failure = { git = "https://github.com/withoutboats/failure/" }
failure_derive = { git = "https://github.com/withoutboats/failure_derive/" }
#failure = "0.1"
#failure_derive = "0.1"
fnorder = "1.0"
lazy_static = "0.2"
log = "0.3"
maplit = "1.0"
matches = "0.1"
rand = "0.3"
regex = "0.2"
rink = "0.4"
serenity = "0.4"
typemap = "0.3"

[features]

default = []
