[package]
name = "eris"
version = "0.3.0"
authors = ["Patrick Burroughs (Celti) <celti@celti.name>"]

[dependencies]
serenity = { git = "https://github.com/zeyla/serenity.git" }
error-chain = "0.10"
regex = "0.2"
lazy_static = "0.2"
rand = "0.3"
rink = "0.4"
