[package]
name = "eris"
version = "0.4.0"
authors = ["Celti Burroughs <celti@celti.name>"]

[dependencies]
chrono = "0.4"
ddate = "0.4"
env_logger = "0.5"
failure = "0.1"
fnorder = "1.0"
indoc = "0.2"
lazy_static = "1.0"
log = "0.4"
maplit = "1.0"
matches = "0.1"
parking_lot = "0.5"
rand = "0.4"
regex = "0.2"
rink = "0.4"
serenity = { version = "0.5", path = "../serenity" }
typemap = "0.3"
log-panics = "2.0"
