[package]
name = "eris"
version = "0.3.3"
authors = ["Patrick Burroughs (Celti) <celti@celti.name>"]

[dependencies]
chrono = "0.4"
error-chain = "0.11"
fnorder = "1.0"
lazy_static = "0.2"
log = "0.3"
maplit = "1.0"
rand = "0.3"
regex = "0.2"
rink = "0.4"
serenity = "0.4"
typemap = "0.3"

clippy = {version = "*", optional = true}

[features]
default = []
