[package]
name = "eris"
version = "0.3.1"
authors = ["Patrick Burroughs (Celti) <celti@celti.name>"]

[dependencies]
serenity = "0.3"
error-chain = "0.10"
regex = "0.2"
lazy_static = "0.2"
rand = "0.3"
rink = "0.4"
fnorder = "1.0"
