[package]
name = "eris"
version = "0.1.0"
authors = ["Celti Burroughs <celti@celti.name>"]
edition = "2018"

[dependencies]
chrono = "0.4"
ddate = "0.4"
diesel = { version = "1.3", features = ["postgres", "chrono"] }
dotenv = "0.13"
exitfailure = "0.5"
failure = "0.1"
fnorder = "1"
lazy_static = "1"
log = "0.4"
log-panics = "2"
maplit = "1"
pretty_env_logger = "0.2"
r2d2 = "0.8"
r2d2-diesel = "1"
rand = "0.5"
regex = "1"
serde = "1"
serde_derive = "1"
serenity = "0.5"
tempfile = "3"
typemap = "0.3"
