cargo-features = ["edition"]

[package]
name = "eris"
version = "0.1.0"
authors = ["Celti Burroughs <celti@celti.name>"]
edition = "2018"

[dependencies]
chrono = "0.4"
ddate = "0.4"
dotenv = "0.13"
env_logger = "0.5"
exitfailure = "0.4"
failure = "0.1"
fnorder = "1"
lazy_static = "1"
libsqlite3-sys = "0.9"
log = "0.4"
log-panics = "2"
maplit = "1"
r2d2 = "0.8"
r2d2_sqlite = "0.5"
rand = "0.5"
regex = "1"
rusqlite = { version = "0.13", features = ["blob", "chrono", "serde_json"] }
serde = "1"
serde_derive = "1"
serde_rusqlite = "0.13"
serenity = "0.5"
typemap = "0.3"
